services:
  mongo_mongo:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-mongodb:v0.0.6
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    env_file:
      - .env.local
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "8083"
        protocol: tcp

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: Chinook
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodata: